#!/bin/sh

### Masqed Crusader for Android (masqedcrusader.conf)
### Version 0.2.0 Open DNS No Ad-Blocking
### Soapbox Apps

# Configuration
no-resolv
no-poll
server=208.67.222.222
server=208.67.220.220
no-dhcp-interface=lo
no-dhcp-interface=eth0
listen-address=127.0.0.1
pid-file=/data/misc/dnsmasq.pid
no-negcache
cache-size=150
log-async=5

