#!/bin/sh

### Masqed Crusader for Android (masqedcrusader.conf)
### Version 0.2.0 Open DNS
### Soapbox Apps

# Configuration
no-resolv
no-poll
server=208.67.222.222
server=208.67.220.220
no-dhcp-interface=lo
no-dhcp-interface=eth0
listen-address=127.0.0.1
pid-file=/data/misc/dnsmasq.pid
no-negcache
cache-size=150
log-async=5

# Ad Filter
address=/p.admob.com/0.0.0.0
address=/analytics.admob.com/0.0.0.0
address=/r.admob.com/0.0.0.0
address=/a.admob.com/0.0.0.0
address=/c.admob.com/0.0.0.0
address=/mm1.vip.sc1.admob.com/0.0.0.0
address=/2mdn.net/0.0.0.0
address=/2o7.net/0.0.0.0
address=/ad-inside.com/0.0.0.0
address=/adbrite.com/0.0.0.0
address=/adinfuse.com/0.0.0.0
address=/admob.com/0.0.0.0
address=/admob.mobi/0.0.0.0
address=/ads.yimg.com/0.0.0.0
address=/adserver.fmpub.net/0.0.0.0
address=/adserver.twitpic.com/0.0.0.0
address=/adserver.yahoo.com/0.0.0.0
address=/adservices.google.com/0.0.0.0
address=/advertising.com/0.0.0.0
address=/adwhirl.com/0.0.0.0
address=/atdmt.com/0.0.0.0
address=/blogads.com/0.0.0.0
address=/dotomi.com/0.0.0.0
address=/doubleclick.be/0.0.0.0
address=/doubleclick.de/0.0.0.0
address=/doubleclick.com/0.0.0.0
address=/doubleclick.net/0.0.0.0
address=/dynamic.fmpub.net/0.0.0.0
address=/fastclick.net/0.0.0.0
address=/flurry.com/0.0.0.0
address=/googleadservices.com/0.0.0.0
address=/greystripe.com/0.0.0.0
address=/iadc.qwapi.com/0.0.0.0
address=/iadsdk.apple.com/0.0.0.0
address=/intellitxt.com/0.0.0.0
address=/juicyads.com/0.0.0.0
address=/jumptap.com/0.0.0.0
address=/m-adx.com/0.0.0.0
address=/mbfr.ad-inside.com/0.0.0.0
address=/mobclix.com/0.0.0.0
address=/modmyads.com/0.0.0.0
address=/mydas.mobi/0.0.0.0
address=/pagead.l.google.com/0.0.0.0
address=/pagead2.googlesyndication.com/0.0.0.0
address=/partnerad.l.google.com/0.0.0.0
address=/qksrv.net/0.0.0.0
address=/quantcast.com/0.0.0.0
address=/quantserve.com/0.0.0.0
address=/reventon.mobi/0.0.0.0
address=/rmxads.com/0.0.0.0
address=/seekmo.com/0.0.0.0
address=/smaato.net/0.0.0.0
address=/static.fmpub.net/0.0.0.0
address=/tapjoy.com/0.0.0.0
address=/tapjoyads.com/0.0.0.0
address=/yieldmanager.com/0.0.0.0
address=/yieldmanager.edgesuite.net/0.0.0.0
address=/yieldmanager.net/0.0.0.0
address=/yoc.mobi/0.0.0.0
address=/zango.com/0.0.0.0
address=/zangocash.com/0.0.0.0
address=/zedo.com/0.0.0.0